### ISSUE TITLE
linux下，把微信支付模块复制到addons目录后，启动odoo报错

### ISSUE THREAD

**Issue by mxx123** [odoo-cn/payment#16]
linux下，把微信支付模块复制到addons目录后，启动odoo报错
2015-06-11 09:57:22,379 23240 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/service/server.py", line 236, in app
    return self.app(e, s)
  File "/opt/odoo/sources/odoo/openerp/service/wsgi_server.py", line 220, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 125, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/service/wsgi_server.py", line 208, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1290, in __call__
    self.load_addons()
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1309, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/sources/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/sources/odoo/addons/payment_weixin/__init__.py", line 22, in <module>
    import models
  File "/opt/odoo/sources/odoo/addons/payment_weixin/models/__init__.py", line 3, in <module>
    import weixin
  File "/opt/odoo/sources/odoo/addons/payment_weixin/models/weixin.py", line 152, in <module>
    class TxWeixin(osv.Model):
  File "/opt/odoo/sources/odoo/addons/payment_weixin/models/weixin.py", line 156, in TxWeixin
    'weixin_txn_id': fields.char('Transaction ID'),
AttributeError: 'module' object has no attribute 'char'

**Comment by jeffery9** [comment]
have fixed. 

please try the lasted code. thanks for your feedback/

**Comment by mxx123** [comment]
此问题已经解决，新问题请见#18
