### ISSUE TITLE
linux下的odoo8里安装微信支付模块时报的错

### ISSUE THREAD

**Issue by mxx123** [odoo-cn/payment#18]
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/sources/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 974, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 3299, in lxml.etree.parse (src/lxml/lxml.etree.c:72655)
  File "parser.pxi", line 1812, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106490)
  File "parser.pxi", line 1832, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:106750)
  File "parser.pxi", line 1727, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:105638)
  File "parser.pxi", line 1146, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:100712)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95050)
XMLSyntaxError: EntityRef: expecting ';', line 24, column 18

**Comment by jeffery9** [comment]
xml error.

 <img t-if="not submit_txt" t-att-src="'/report/barcode/?type=%s&va    lue=%s&width=%s&height=%s'%('QR', t-esc=' tx_values['qrcode']', 200, 200)"/>

**Comment by mxx123** [comment]
这个问题解决了，但又有了新的问题，页面上方显示出好几个静态css文件没找到（比如web.assets_backend等），并且页面的布局也都乱了.另外，#16的那个问题在财付通支付模块里也出现了

**Comment by jeffery9** [comment]
if have no weixin payment account, it should report error like this

![image](https://cloud.githubusercontent.com/assets/1404460/8128771/c9a3c3a2-1134-11e5-9447-c4eadaa8b271.png)

**Comment by mxx123** [comment]
此问题已解决，是由于linux权限问题
