### ISSUE TITLE
我设置了微信支付账号后，在odoo页面操作时报错FAIL, invalid spbill_create_ip

### ISSUE THREAD

**Issue by mxx123** [odoo-cn/payment#26]
我设置了微信支付账号后，在odoo页面操作时，在最后那步选择付款方式页面，报错FAIL, invalid spbill_create_ip

Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/addons/website/models/ir_http.py", line 204, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/sources/odoo/openerp/http.py", line 677, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/website_sale/controllers/main.py", line 668, in payment
    context=render_ctx)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/payment/models/payment_acquirer.py", line 253, in render
    partner_values, tx_values = method(cr, uid, id, partner_values, tx_values, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/additionnal_addons/payment_weixin/models/weixin.py", line 147, in weixin_form_generate_values
    raise ValidationError("%s, %s" % (return_code, return_msg))
ValidationError: FAIL, invalid spbill_create_ip

**Comment by jeffery9** [comment]
应该是 取spbill_create_ip 的值 不对，尽快修复。
谢谢 反馈

**Comment by jeffery9** [comment]
你使用nginx 做反向代理了吗，如果是，需要设置正确的 HOST 参数

因为微信需要提供 发起支付请求的服务器的IP地址

    def _get_ipaddress(self):
        return request.httprequest.environ['HTTP_HOST']



代码里面 取主机IP地址是通过`HTTP_HOST`进行的
